name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install
      
      - name: Audit dependencies
        if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
        run: npm audit

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: brave-builds[bot]
          user_email: brave-builds@brave.com
